[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "node server.js"
  port = 3000
  publish = "public"
  functions = "netlify/functions"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/calculate"
  to = "/.netlify/functions/calculate-impact"
  status = 200

[[redirects]]
  from = "/api/ai-analysis"
  to = "/.netlify/functions/generate-ai-analysis"
  status = 200

[[redirects]]
  from = "/api/calculate-mitigation"
  to = "/.netlify/functions/calculate-mitigation"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
